### ISSUE TITLE
This is the first issue

### ISSUE THREAD

**Issue by StiftungAusNachlass** [programmfabrik/easydb-external-developers#1]
This is the first issue

**Comment by martinrode** [comment]
Testantwort

**Comment by StiftungAusNachlass** [comment]
Who is allowed to close issues? Is there any editorial staff or is this open for all?

**Comment by StiftungAusNachlass** [comment]
But i'm not allowed to set Labels

**Comment by KlausThornProgrammfabrik** [comment]
Issues on this repository are not observed, so we suggest to contact the developers directly or support@programmfabrik.de if their contribution is relevant to the issue.
